### ISSUE TITLE
Documentation on Notification Icon Example

### ISSUE THREAD

**Issue by robert589** [pushy-me/pushy-react-native#22]
> Optionally configure a custom notification icon for incoming Android notifications by placing icon file(s) in android/app/src/main/res/drawable-* and calling:
> 
> Pushy.setNotificationIcon('ic_notification');
> Replace ic_notification with the resource file name, excluding the extension.
> 
> Note: If you don't call this method, or an invalid resource is provided, a generic icon will be used instead.

Where can I place the Pushy.setNotificationIcon, I have placed it in several places but what i get is a complete gray icon instead

**Comment by pushy-me** [comment]
Hi @robert589,
Thanks for the suggestion, we have just updated the docs to state that this method should be called after `Pushy.listen()`.

If you are seeing a gray icon instead of your configured icon:
1) Make sure you are using a black-or-white icon, without any colors, for your notification icon.
2) Make sure you are referencing the drawable name correctly, without the extension.

E.g. if your icon is located in:
```
android/app/src/main/res/drawable-hdpi/ic_notification.png
```

Configure it as the notification icon as follows, without the extension:
```
Pushy.setNotificationIcon('ic_notification');
```

**Comment by robert589** [comment]
I see some phones actually have color while some phones dont have color. 

Do u know the explanation behind this?

**Comment by robert589** [comment]
Hi, I have tried and still not working
Is there any way to debug this?

**Comment by robert589** [comment]
ok, u need to use generic icon generator to convert your icon like this one.
https://icons.learnpainless.com/icons-notification.html#source.space.trim=1&source.space.pad=0&name=ic_stat_example

**Comment by robert589** [comment]
Hi, Do you guys use setsmallicon or setlargeicon in the api?

**Comment by robert589** [comment]
Hi, SetNotificationIcon not working in IOS

**Comment by pushy-me** [comment]
Hi @robert589,
1) The SDK uses `builder.setSmallIcon()` with the icon resource provided to `Pushy.setNotificationIcon('ic_notification')`. The SDK does not call `builder.setLargeIcon()`.

2) For iOS, you cannot change the icon of the notification dynamically [(source)](https://stackoverflow.com/a/34620273/1123355). iOS will use your app's launcher icon or another specifically-designated notification icon in your app's icon bundle.
